### ISSUE TITLE
SPEC-7: random numbers

### ISSUE THREAD

**Issue by bsipocz** [scientific-python/summit-2024#11]
Wrapping up the SPEC (https://github.com/scientific-python/specs/pull/180) and identifying and implementing any support tooling that would help with ecosystem adoption.

**Comment by betatim** [comment]
I might attempt making a change to scikit-learn that starts using the new random number infrastructure from Numpy. This is kind of related to the SPEC. The goal would be to find out about all the things we haven't thought of and getting a better idea how hard such a transition would be to do. However, amongst all the things that could receive attention in scikit-learn I think this topic doesn't have a great "reviewer time required/benefit" ratio. Mostly because transitioning all of the library would require a lot of review. Trying to get started would still be interesting though to see what happens.

**Comment by bsipocz** [comment]
Obviously I can't help with the review part, but can definitely help with making the changes to the code.

**Comment by thomasjpfan** [comment]
For scikit-learn, we wanted to use NumPy's new Generator API to solve a long running API problem around scikit-learn + random number generators. It turns out the API problem is a bit more complex, so it stalled Generator adoption. For me, I find the story around Generators + multiple processes very appealing.

If a library wanted to treat the new `Generator` the same as `RandomState`, then it mostly just works out of the box. The only big API difference are integers. SciPy has their own helper function to sample integers:

https://github.com/scipy/scipy/blob/1ba35d1c4f66d82e0d395cf086e2212c06d8852d/scipy/_lib/_util.py#L518-L524
